// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlgieodsfuaoackcpwoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZ2llb2RzZnVhb2Fja2Nwd29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjA4ODYsImV4cCI6MjA2NzYzNjg4Nn0.10SXg1POwlg0s2gB1jWEVgjgXYTWpbWw2GUhCHvnuBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});